//components/destinations.js
// Single source of truth for all destination data

export const ALL_DESTINATIONS = [
  {
    id: 1,
    name: 'Okavango Delta', location: 'Maun', region: 'North-West',
    lat: -19.0154, lng: 22.8544,
    price: 4500, priceLabel: 'P 4,500', rating: 4.9, reviews: 312,
    category: 'Safari', match: 97,
    tag: 'Top Pick', tagColor: 'bg-blue-50 text-blue-600',
    photo: '/images/destinations/okavango-delta.jpg',
    gradient: 'from-blue-100 to-cyan-50',
    desc: "UNESCO World Heritage Site. Explore the world's largest inland delta by mokoro canoe through pristine waterways teeming with wildlife.",
    features: ['Wildlife', 'Photography', 'Mokoro', 'Luxury'],
    aiReason: 'Matches your wildlife photography preference',
  },
  {
    id: 2,
    name: 'Chobe National Park', location: 'Kasane', region: 'North',
    lat: -17.7990, lng: 24.7666,
    price: 5100, priceLabel: 'P 5,100', rating: 4.8, reviews: 287,
    category: 'Game Reserve', match: 93,
    tag: 'Trending', tagColor: 'bg-rose-50 text-rose-600',
    photo: 'images/destinations/ChatGPT Image Mar 19, 2026, 12_28_55 AM.png',
    gradient: 'from-emerald-100 to-green-50',
    desc: "Home to Africa's densest elephant population. Epic river cruises at golden hour with hundreds of elephants crossing.",
    features: ['Elephants', 'River Cruise', 'Big 5', 'Birding'],
    aiReason: 'Popular with users who share your booking history',
  },
  {
    id: 3,
    name: 'Makgadikgadi Pans', location: 'Nata', region: 'North-East',
    lat: -20.4500, lng: 25.8000,
    price: 3200, priceLabel: 'P 3,200', rating: 4.7, reviews: 198,
    category: 'Landscape', match: 88,
    tag: 'Hidden Gem', tagColor: 'bg-amber-50 text-amber-600',
    photo: '/images/destinations/makgadikgadi.jpg',
    gradient: 'from-amber-100 to-yellow-50',
    desc: 'Vast salt flats stretching to the horizon. During rainy season thousands of flamingos transform the landscape into a sea of pink.',
    features: ['Flamingos', 'Stargazing', 'Landscape', 'Quad Biking'],
    aiReason: 'Aligns with your interest in open landscapes',
  },
  {
    id: 4,
    name: 'Central Kalahari Game Reserve', location: 'Ghanzi', region: 'Central',
    lat: -21.7500, lng: 23.5833,
    price: 2900, priceLabel: 'P 2,900', rating: 4.6, reviews: 154,
    category: 'Desert', match: 82,
    tag: 'Adventure', tagColor: 'bg-orange-50 text-orange-600',
    photo: 'images/destinations/ChatGPT Image Mar 19, 2026, 12_26_13 AM.png',
    gradient: 'from-orange-100 to-amber-50',
    desc: "One of the world's largest game reserves. Authentic Bushmen cultural experiences in the ancient red sands of the Kalahari.",
    features: ['Culture', 'Desert', 'Lions', 'Camping'],
    aiReason: 'Recommended for adventure seekers',
  },
  {
    id: 5,
    name: 'Moremi Game Reserve', location: 'Moremi', region: 'North-West',
    lat: -19.1667, lng: 23.2500,
    price: 4800, priceLabel: 'P 4,800', rating: 4.8, reviews: 243,
    category: 'Game Reserve', match: 91,
    tag: 'Premium', tagColor: 'bg-purple-50 text-purple-600',
    photo: '/images/destinations/moremi.jpg',
    gradient: 'from-purple-100 to-violet-50',
    desc: 'Where the Okavango meets the Kalahari. Year-round Big Five sightings in the most biodiverse corner of Botswana.',
    features: ['Big Five', 'Birding', 'Photography', 'Luxury'],
    aiReason: 'Highly rated by users with similar preferences',
  },
  {
    id: 6,
    name: 'Nxai Pan National Park', location: 'Maun', region: 'North-West',
    lat: -19.9167, lng: 24.7500,
    price: 2600, priceLabel: 'P 2,600', rating: 4.5, reviews: 121,
    category: 'Safari', match: 79,
    tag: 'Value', tagColor: 'bg-emerald-50 text-emerald-600',
    photo: '/images/destinations/nxai_pan.jpg',
    gradient: 'from-green-100 to-emerald-50',
    desc: "Ancient fossil pan home to the iconic Baines' Baobabs. Witness the zebra migration corridor and predator action up close.",
    features: ['Baobabs', 'Zebras', 'Stargazing', 'Family'],
    aiReason: 'Great value option matching your budget range',
  },
  {
    id: 7,
    name: 'Tsodilo Hills', location: 'Shakawe', region: 'North-West',
    lat: -18.7500, lng: 21.7333,
    price: 1800, priceLabel: 'P 1,800', rating: 4.6, reviews: 98,
    category: 'Heritage', match: 76,
    tag: 'Cultural', tagColor: 'bg-pink-50 text-pink-600',
    photo: '/images/destinations/tsodilo.jpg',
    gradient: 'from-pink-100 to-rose-50',
    desc: "UNESCO World Heritage Site with over 4,500 San rock paintings. Known as the 'Louvre of the Desert'.",
    features: ['Rock Art', 'Culture', 'Hiking', 'Heritage'],
    aiReason: 'Matches your interest in cultural experiences',
  },
  {
    id: 8,
    name: 'Khama Rhino Sanctuary', location: 'Serowe', region: 'Central',
    lat: -22.3833, lng: 26.7167,
    price: 1500, priceLabel: 'P 1,500', rating: 4.4, reviews: 87,
    category: 'Safari', match: 74,
    tag: 'Conservation', tagColor: 'bg-teal-50 text-teal-600',
    photo: '/images/destinations/khama.jpg',
    gradient: 'from-teal-100 to-cyan-50',
    desc: 'Community-owned sanctuary protecting white and black rhinos. One of the few places in Botswana to see rhinos up close.',
    features: ['Rhinos', 'Conservation', 'Walking Safari', 'Community'],
    aiReason: 'Recommended for conservation-minded travellers',
  },
  {
    id: 9,
    name: 'Savuti Marsh', location: 'Chobe', region: 'North',
    lat: -18.5500, lng: 24.0667,
    price: 3800, priceLabel: 'P 3,800', rating: 4.7, reviews: 176,
    category: 'Game Reserve', match: 85,
    tag: 'Wildlife', tagColor: 'bg-yellow-50 text-yellow-600',
    photo: '/images/destinations/savuti.jpg',
    gradient: 'from-yellow-100 to-amber-50',
    desc: 'Famous for large lion prides and massive elephant herds. Dramatic predator-prey interactions year-round.',
    features: ['Lions', 'Elephants', 'Game Drive', 'Predators'],
    aiReason: 'Top pick for wildlife action seekers',
  },
  {
    id: 10,
    name: 'Linyanti Wetlands', location: 'Linyanti', region: 'North',
    lat: -17.9833, lng: 23.9167,
    price: 5500, priceLabel: 'P 5,500', rating: 4.9, reviews: 134,
    category: 'Safari', match: 89,
    tag: 'Exclusive', tagColor: 'bg-indigo-50 text-indigo-600',
    photo: '/images/destinations/linyanti.jpg',
    gradient: 'from-indigo-100 to-blue-50',
    desc: 'Remote luxury wilderness where the Linyanti River meets vast floodplains. Exclusive camps with world-class game viewing.',
    features: ['Luxury', 'Remote', 'Wild Dogs', 'Boat Safari'],
    aiReason: 'Perfect for exclusive luxury safari experiences',
  },
  {
    id: 11,
    name: 'Tuli Block', location: 'Selebi-Phikwe', region: 'East',
    lat: -22.1833, lng: 29.1833,
    price: 3100, priceLabel: 'P 3,100', rating: 4.5, reviews: 109,
    category: 'Game Reserve', match: 78,
    tag: 'Scenic', tagColor: 'bg-lime-50 text-lime-600',
    photo: '/images/destinations/tuli.jpg',
    gradient: 'from-lime-100 to-green-50',
    desc: "Ancient rock formations and baobab-studded landscape on Botswana's eastern border. Excellent horseback safaris.",
    features: ['Horseback', 'Baobabs', 'Rock Art', 'Elephants'],
    aiReason: 'Ideal for unique horseback safari experiences',
  },
  {
    id: 12,
    name: 'Gcwihaba Caves', location: 'Ghanzi', region: 'North-West',
    lat: -20.1167, lng: 21.6833,
    price: 1200, priceLabel: 'P 1,200', rating: 4.3, reviews: 67,
    category: 'Adventure', match: 71,
    tag: 'Unique', tagColor: 'bg-slate-50 text-slate-600',
    photo: '/images/destinations/gcwihaba.jpg',
    gradient: 'from-slate-100 to-gray-50',
    desc: "Botswana's only significant cave system with stunning stalactites and stalagmites, sacred to the San people.",
    features: ['Caves', 'Adventure', 'San Culture', 'Unique'],
    aiReason: 'Off-the-beaten-path adventure destination',
  },
  {
    id: 13,
    name: 'Kgalagadi Transfrontier Park', location: 'Tsabong', region: 'South',
    lat: -25.4000, lng: 21.8333,
    price: 2400, priceLabel: 'P 2,400', rating: 4.6, reviews: 142,
    category: 'Desert', match: 80,
    tag: 'Cross-Border', tagColor: 'bg-red-50 text-red-600',
    photo: '/images/destinations/kgalagadi.jpg',
    gradient: 'from-red-100 to-orange-50',
    desc: 'Shared peace park between Botswana and South Africa. Famous for black-maned Kalahari lions and massive dune landscapes.',
    features: ['Kalahari Lions', 'Desert', 'Raptors', 'Dunes'],
    aiReason: 'Great for Kalahari desert and lion enthusiasts',
  },
  {
    id: 14,
    name: 'Mokolodi Nature Reserve', location: 'Gaborone', region: 'South',
    lat: -24.7167, lng: 25.9333,
    price: 900, priceLabel: 'P 900', rating: 4.3, reviews: 203,
    category: 'Safari', match: 68,
    tag: 'Family', tagColor: 'bg-green-50 text-green-600',
    photo: '/images/destinations/mokolodi.jpg',
    gradient: 'from-green-100 to-emerald-50',
    desc: "Botswana's most accessible nature reserve just outside Gaborone. Perfect for families with rhino encounters and guided bush walks.",
    features: ['Family', 'Rhinos', 'Bush Walk', 'Accessible'],
    aiReason: 'Best value day trip from Gaborone',
  },
  {
    id: 15,
    name: 'Gaborone Game Reserve', location: 'Gaborone', region: 'South',
    lat: -24.6550, lng: 25.9120,
    price: 600, priceLabel: 'P 600', rating: 4.1, reviews: 178,
    category: 'Safari', match: 65,
    tag: 'City Escape', tagColor: 'bg-cyan-50 text-cyan-600',
    photo: '/images/destinations/gaborone-reserve.jpg',
    gradient: 'from-cyan-100 to-sky-50',
    desc: 'Urban wildlife sanctuary in the heart of the capital. Spot zebras, wildebeest and giraffes minutes from the city centre.',
    features: ['Urban Safari', 'Zebras', 'Giraffes', 'Day Trip'],
    aiReason: 'Perfect quick escape for Gaborone residents',
  },
];

export const CATEGORIES = ['All', 'Safari', 'Game Reserve', 'Landscape', 'Desert', 'Heritage', 'Adventure'];
export const REGIONS    = ['All Regions', 'North-West', 'North', 'North-East', 'Central', 'East', 'South'];
export const SORT_OPTIONS = ['Best Match', 'Highest Rated', 'Price: Low to High', 'Price: High to Low'];